
import React from "react";
import AdminLayout from "../Layout/AdminLayout";

function Dashboard() {

  return (
    <AdminLayout>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
      <h2>Welcome dashboard</h2>
    </AdminLayout>
  );
}

export default Dashboard;
